### ISSUE TITLE
SQLAlchemy >= 1.3 incompatibility

### ISSUE THREAD

**Issue by vidakDK** [ndparker/gensaschema#2]
Since version 1.3 of SA `convert_unicode` is [deprecated](https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.Enum.params.convert_unicode), so generating schema for any text/char fields fails. 

Example when trying to generate a schema with a `TEXT` field (same happens for `VARCHAR`):
```
Traceback (most recent call last):
 ...
  File "/Users/vidak.kazic/.virtualenvs/pm-sem/lib/python3.7/site-packages/st/cs/db/cmdline.py", line 57, in cmd_schema
    schema_obj.dump(fp)
  File "/Users/vidak.kazic/.virtualenvs/pm-sem/lib/python3.7/site-packages/gensaschema/_schema.py", line 163, in dump
    lines.append('%s = %r' % (table.varname, table))
  File "/Users/vidak.kazic/.virtualenvs/pm-sem/lib/python3.7/site-packages/gensaschema/_table.py", line 229, in __repr__
    for col in self.sa_table.columns
  File "/Users/vidak.kazic/.virtualenvs/pm-sem/lib/python3.7/site-packages/gensaschema/_table.py", line 229, in <listcomp>
    for col in self.sa_table.columns
  File "/Users/vidak.kazic/.virtualenvs/pm-sem/lib/python3.7/site-packages/gensaschema/_column.py", line 159, in __repr__
    params = list(map(repr, (self._name, self._ctype)))
  File "/Users/vidak.kazic/.virtualenvs/pm-sem/lib/python3.7/site-packages/gensaschema/_type.py", line 134, in __repr__
    value = getattr(self._ctype, arg.name)
AttributeError: 'TEXT' object has no attribute 'convert_unicode'
```

**Comment by ndparker** [comment]
Thanks. Luckily the tests could reproduce that easily. It should be fixed in version 0.6.4 (hot off the press).
